site_name: Data Engineering
site_description: Data Engineering class at ISAE-Supaero as part of the SDD program
site_url: https://supaerodatascience.github.io/DE/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/DE/master/src/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/DE/master/src/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: SupaeroDataScience/DE
repo_url: https://github.com/SupaeroDataScience/DE

nav:
- Overview:
  - Syllabus: index.md
- DE Fundamentals:
  - CTF: ctf.md
- Data Storage:
  - SQL: 0_1_databases.md
  - PostgreSQL: 0_3_postgres.md
  - ETL: 
    - Lecture: 0_2_ETL.md
    - TP: 0_5_airlife.md
  - Project: 0_4_project.md
- Data Computation:
  - Introduction: 1_1_overview.md
  - Cloud Computing & Google Cloud Platform:
    - 1. Lecture: 1_2a_cloud.md
    - 2. Hands-on (Setup): 1_2b_handson_setup.md
    - 3. Hands-on (Remote Development): 1_2c_handson_codespace.md
    - 4. Hands-on (GCP): 1_2d_handson_gcp.md
  - Containers, Docker:
    - 1. Lecture: 1_3a_containers.md
    - 2. Hands-on (Docker): 1_3b_handson_docker.md
  - Workshop GCP & Docker:
    - 1. Docker Workflow: 1_4a_docker_workflow.md
    - 2. GCP Compute Workflow: 1_4b_gcp_workflow.md
    - 3. GCP Deployment Workflow: 1_4c_deployment_workflow.md
  - Workshop Deploy your ML model into production:
    - 1. Lecture: 1_5a_deployment.md
    - 2. Deploy your ML model into production: 1_5b_deployment_be.md
  - Recap & Reading List: 1_6_conclusion.md
  - Appendixes & Technical Notions : 1_7_appendixes.md
- Data Distribution:
  - Introduction:
    - Overview: 2_1_overview.md
    - Hadoop and MapReduce: 2_5_mapreduce.md
  - Orchestration & Kubernetes:
    - Lectures: 2_2_orchestration.md
    - TP: 2_3_kub_handson.md
  - Spark: 2_6_spark.md
  - Dask on Kubernetes: 2_8_dask.md
  - Dask project: 2_9_project.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: ðŸ”—
- admonition
- codehilite
- extra
- attr_list
- def_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
